version: "3"

services:
    frontend:
        container_name: nomt-frontend
        build:
            context: ./client
            dockerfile: Dockerfile
        image: nomt/frontend
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
            # - ./client:/app/node_modules
        stdin_open: true

    backend:
        container_name: nomt-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: nomt/backend
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app