export const lessonData = {
  satreasoning: {
    reading: {
      name: 'Цэлмэг',
      image: 'tselmeg',
      university: 'UC Berkeley',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/eqycndPS-xg', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/iNGr9wAP2No', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/QVPUSSRTez4', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/_a9fNwwq6r8', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/rI3WLOpgGLk', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/OYGiwUGopRU', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/pB3PyrU9oPA', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/5BMyuNvud88', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/qA84MCnUqC8', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/QT8WEVMJUVs', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/Lwd2ZZ8Guw0', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/miaBt6VM3oc', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/gz6zWQ1C9y8', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/83cOK5Chep0', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/mM6DC1HUsck', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/cWo4fsUQiPU', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/VOL3j5xHPFQ', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/WldP9BsrMQs', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/DXGX9TuuKm0', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/pDAQeF9Lrf8', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/diMqbjAk7l4', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/D6YQmvXxAZA', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/CJ2N-jrPOuY', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/61otQGELtZI', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/tRRvljGNQ20', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/tRRvljGNQ20', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/u5eaCWr6ctI', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/FGC-V2t6qNg', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/d06SWJwJp5M', time: '00.25.23' },
      ]
    },
    writing: {
      name: 'Цэлмэг',
      image: 'tselmeg',
      university: 'UC Berkeley',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/sKZztEwOxtI', time: '00.20.00' },
        { name: 'Lesson-2', link: 'https://youtu.be/88bXaZBWAqU', time: '00.20.45' },
        { name: 'Lesson-3', link: 'https://youtu.be/OATd1YLuICE', time: '00.20.40' },
        { name: 'Lesson-4', link: 'https://youtu.be/lFp0XXM9agc', time: '00.21.02' },
        { name: 'Lesson-5', link: 'https://youtu.be/0I0e9f-ltM0', time: '00.20.13' },
        { name: 'Lesson-6', link: 'https://youtu.be/BWAt3cvbYvU', time: '00.22.05' },
        { name: 'Lesson-7', link: 'https://youtu.be/0I0e9f-ltM0', time: '00.24.52' },
        { name: 'Lesson-8', link: 'https://youtu.be/TQ5qgIgMK0k', time: '00.20.30' },
        { name: 'Lesson-9', link: 'https://youtu.be/NcSvWhTmumo', time: '00.20.56' },
        { name: 'Lesson-10', link: 'https://youtu.be/EzqvWT8tVjA', time: '00.20.21' },
        { name: 'Lesson-11', link: 'https://youtu.be/ZcTyuXCJtEI', time: '00.31.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/sbRCyhyjAoU', time: '00.20.06' },
        { name: 'Lesson-13', link: 'https://youtu.be/y77DioyCRmI', time: '00.20.01' },
        { name: 'Lesson-14', link: 'https://youtu.be/aPEGwe2mgyY', time: '00.20.22' },
        { name: 'Lesson-15', link: 'https://youtu.be/__xw_R2xwew', time: '00.21.45' },
        { name: 'Lesson-16', link: 'https://youtu.be/jZEq7b1lKlA', time: '00.20.39' },
        { name: 'Lesson-17', link: 'https://youtu.be/FH2tStAi1gI', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/ganCZoAjYKg', time: '00.25.19' },
        { name: 'Lesson-19', link: 'https://youtu.be/C_32k5R8zNQ', time: '00.23.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/i3CgvLaVM80', time: '00.21.15' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/keZGLNA1SaQ', time: '00.29.41' },
        { name: 'Lesson-23', link: 'https://youtu.be/RbeoMezHflk', time: '00.27.58' },
        { name: 'Lesson-24', link: 'https://youtu.be/hDzLIBh7qTs', time: '00.22.08' },
        { name: 'Lesson-25', link: 'https://youtu.be/WxBgJLrKYuM', time: '00.20.55' },
        { name: 'Lesson-26', link: 'https://youtu.be/Iv33YDIJyLM', time: '00.23.27' },
        { name: 'Lesson-27', link: 'https://youtu.be/KCm1GxQGB1Y', time: '00.24.18' },
        { name: 'Lesson-28', link: 'https://youtu.be/pKWEBlutVt0', time: '00.17.17' },
        { name: 'Lesson-29', link: 'https://youtu.be/S5kxLCPPbCw', time: '00.22.38' },
        { name: 'Lesson-30', link: 'https://youtu.be/0BkmtExb440', time: '00.23.34' }
      ]
    },
    mathematics: {
      name: 'Эзэнбаатар',
      image: 'ezenbaatar',
      university: 'Kansas',
      score: 'Test score: HSK6-256',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    essey: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  satsubjects: {
    physics: {
      name: 'ЦОЛМОН',
      image: 'tsolmon',
      university: 'MIT',
      score: 'Test score: SAT Subject Test Physics оноо: 800',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'math%20lvl%202': {
      name: 'Оргилбат',
      image: 'huslen',
      university: 'University of Colorado boulder',
      score: 'Хотын физикийн олимпиадын тэргүүн байр',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    chemistry: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    biology: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'American%20History': {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  ielts: {
    reading: {
      name: 'Баясгалан',
      image: 'bayasgalan',
      university: 'NYU SHANGHAI',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    listening: {
      name: 'Мандах',
      image: 'mandah',
      university: 'Melbourne Uni',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    writing: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    speaking: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  toefl: {
    reading: {
      name: 'Баясгалан',
      image: 'bayasgalan',
      university: 'NYU SHANGHAI',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    listening: {
      name: 'Мандах',
      image: 'mandah',
      university: 'Melbourne Uni',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    writing: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    speaking: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  monbusho: {
    mathematics: {
      name: 'Билгүүн',
      image: 'bilguun',
      university: 'Tohoku university',
      score: 'Улсын физикийн олимпиадын тусгай байр',
      price: "59'900₮",
      lessons: [
        { name: 'College-2015', link: 'https://youtu.be/https://youtu.be/4X85Sm1wWMQ', time: '01.16.09' },
        { name: 'College-2016', link: 'https://youtu.be/https://youtu.be/83z4TLyUa1k', time: '01.28.44' },
        { name: 'Log and Lim', link: 'https://youtu.be/https://youtu.be/dewjotGc7Uk', time: '01.04.31' },
        { name: 'Ulamjlal', link: 'https://youtu.be/https://youtu.be/PsNPFvJ5KAs', time: '00.45.29' },
        { name: 'University 2016 Anemsen', link: 'https://youtu.be/https://youtu.be/DDe_sVqHZWA', time: '01.09.54' },
        { name: 'University 2016 B', link: 'https://youtu.be/https://youtu.be/smllP2xCUSE', time: '00.51.10' },
        { name: 'Matrix', link: 'https://youtu.be/https://youtu.be/E9UFIgPY8KY', time: '01.34.00' },
        { name: 'Integral', link: 'https://youtu.be/https://youtu.be/vD2cDHtrcwo', time: '00.36.09' }
      ]
    },
    Physics: {
      name: 'Сайнбилэгт',
      image: 'sainbilegt',
      university: 'Tohoku university',
      score: 'Улсын физикийн олимпиадын мөнгө, хүрэл медал хүртсэн',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1: Kinematics', link: 'https://youtu.be/xoe5fWoOikM', time: '00.51.24' },
        { name: 'Lesson-2: Part-1 Dynamics', link: 'https://youtu.be/XUugp7RxmbM', time: '00.35.37' },
        { name: 'Lesson-2: Part-2 Energy and impulse', link: 'https://youtu.be/TgdZbDgo69Q', time: '00.29.19' },
        { name: 'lesson-3: Molecular kinetic theory', link: 'https://youtu.be/plczs83eQeg', time: '00.29.37' },
        { name: 'Lesson-4: Termodinamics', link: 'https://youtu.be/TpQdGNyXmyo', time: '00.38.04' },
        { name: 'Lesson-5: Electrostatics', link: 'https://youtu.be/bgAxbybQ-X0', time: '00.32.51' },
        { name: 'Lesson-6: Electric circuits Part-1', link: 'https://youtu.be/yvgIoQgz0wE', time: '00.37.33' },
        { name: 'Lesson-6: Electric circuits Part-2', link: 'https://youtu.be/sXXbNySObeQ', time: '00.22.34' },
        { name: 'Lesson-7: Part-1 Magnetics', link: 'https://youtu.be/ygPboPIrvP4', time: '00.22.23' },
        { name: 'Lesson-7: Part-2 Induction', link: 'https://youtu.be/_vKbh3JSq6M', time: '00.30.51' },
        { name: 'Lesson-8: Part-1 Oscillation and Wave', link: 'https://youtu.be/iHBQciDXEuk', time: '00.33.55' },
        { name: 'Lesson-8: Part-2 Dopler', link: 'https://youtu.be/-ym9sZVqXiA', time: '00.16.05' },
        { name: 'Lesson-9: Optics', link: 'https://youtu.be/gRZnA-W7HKQ', time: '00.38.28' },
        { name: 'Lesson-10: Extra', link: 'https://youtu.be/j5JPb0O59xo', time: '00.37.04' }
      ]
    },
    japanese: {
      name: 'Ялгум',
      image: 'ylgum',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    chemistry: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  hsk: {
    'hsk-1': {
      name: 'Ану',
      image: 'anu',
      university: 'Tongji Medical University of Hust',
      score: 'Test score: HSK6-256',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'hsk-2': {
      name: 'Ану',
      image: 'anu',
      university: 'Tongji Medical University of Hust',
      score: 'Test score: HSK6-256',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'hsk-3': {
      name: 'Ану',
      image: 'anu',
      university: 'Tongji Medical University of Hust',
      score: 'Test score: HSK6-256',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'hsk-4': {
      name: 'Ану',
      image: 'anu',
      university: 'Tongji Medical University of Hust',
      score: 'Test score: HSK6-256',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  undergraduate: {
    japan: {
      name: 'Сайнбилэгт',
      image: 'sainbilegt',
      university: 'Tohoku university',
      score: 'Улсын физикийн олимпиадын мөнгө, хүрэл медал хүртсэн',
      price: "59'900₮",
      lessons: [
        { name: 'Road to Japan', link: 'https://youtu.be/HZcUtAtjI3U', time: '00.31.32' }
      ]
    },
    USA: {
      name: 'Намуунгоо',
      image: 'namuungoo',
      university: 'Harvard',
      score: 'Test score: SAT: 1490 SAT Math lvl2: 800 IELTS: 8.0',
      price: "59'900₮",
      lessons: [
        { name: 'Part 1 Back to The Basics', link: 'https://youtu.be/aS3W2_5iIvI', time: '00.17.49' },
        { name: 'Part 2 Planning', link: 'https://youtu.be/w8KZS8p53kI', time: '00.23.14' },
        { name: 'Part 3 Building Your College List', link: 'https://youtu.be/QU7PMwpaSn8', time: '00.27.20' },
        { name: 'Part 4 Financing Your Education', link: 'https://youtu.be/EeqNjELUgLM', time: '00.11.32' },
        { name: 'Part 5 How To Be The Student Colleges Want', link: 'https://youtu.be/o0uvlpwI2xo', time: '00.22.26' },
        { name: 'Part 6 Common Application Coalition Application', link: 'https://youtu.be/BdIsMaFzyQE', time: '00.26.52' }
      ]
    },
    german: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    Hungary: {
      name: '',
      image: '',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  },
  programm: {
    html: {
      name: 'Мөнхжавхлан',
      image: 'javkhaa',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    'c++': {
      name: 'Золбоо',
      image: 'zolboo',
      university: '',
      score: '',
      price: '59 900₮',
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    },
    css: {
      name: 'Мөнхжавхлан',
      image: 'javkhaa',
      university: '',
      score: '',
      price: "59'900₮",
      lessons: [
        { name: 'Lesson-1', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-2', link: 'https://youtu.be/', time: '00.27.09' },
        { name: 'Lesson-3', link: 'https://youtu.be/', time: '00.23.00' },
        { name: 'Lesson-4', link: 'https://youtu.be/', time: '00.41.23' },
        { name: 'Lesson-5', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-6', link: 'https://youtu.be/', time: '00.37.18' },
        { name: 'Lesson-7', link: 'https://youtu.be/', time: '00.21.07' },
        { name: 'Lesson-8', link: 'https://youtu.be/', time: '00.42.57' },
        { name: 'Lesson-9', link: 'https://youtu.be/', time: '00.28.29' },
        { name: 'Lesson-10', link: 'https://youtu.be/', time: '00.31.36' },
        { name: 'Lesson-11', link: 'https://youtu.be/', time: '00.21.02' },
        { name: 'Lesson-12', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-13', link: 'https://youtu.be/', time: '00.30.55' },
        { name: 'Lesson-14', link: 'https://youtu.be/', time: '00.26.23' },
        { name: 'Lesson-15', link: 'https://youtu.be/', time: '00.28.50' },
        { name: 'Lesson-16', link: 'https://youtu.be/', time: '00.20.02' },
        { name: 'Lesson-17', link: 'https://youtu.be/', time: '00.20.01' },
        { name: 'Lesson-18', link: 'https://youtu.be/', time: '00.20.15' },
        { name: 'Lesson-19', link: 'https://youtu.be/', time: '00.24.35' },
        { name: 'Lesson-20', link: 'https://youtu.be/', time: '00.25.49' },
        { name: 'Lesson-21', link: 'https://youtu.be/', time: '00.28.22' },
        { name: 'Lesson-22', link: 'https://youtu.be/', time: '00.26.43' },
        { name: 'Lesson-23', link: 'https://youtu.be/', time: '00.25.24' },
        { name: 'Lesson-24', link: 'https://youtu.be/', time: '00.31.49' },
        { name: 'Lesson-25', link: 'https://youtu.be/', time: '00.30.05' },
        { name: 'Lesson-26', link: 'https://youtu.be/', time: '00.25.02' },
        { name: 'Lesson-27', link: 'https://youtu.be/', time: '00.22.45' },
        { name: 'Lesson-28', link: 'https://youtu.be/', time: '00.22.56' },
        { name: 'Lesson-29', link: 'https://youtu.be/', time: '00.25.23' },
      ]
    }
  }
}
